<a href="https://colab.research.google.com/github/OniOnizukazuka/PyTorchBeginner/blob/main/PyTorchBeginner02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Tensor Basics - PyTorch Beginner 02](https://www.python-engineer.com/courses/pytorchbeginner/01-installation/)

# **02 Tensor Basics**
This part covers the basics of Tensors and Tensor operations in PyTorch. Learn also how to convert from numpy data to PyTorch tensors and vice versa!

## Tensor
Everything in PyTorch is based on Tesor operations. A tensor can have different dimensions, so it can be 1d(scalar), 2d(vector), or even 3d(matrix) and higher. Let's have a look how we can create a tensor in PyTorch.

In [17]:
import torch

x = torch.empty(1) #scalar
print(x)

tensor([9.0413e-38])


In [18]:
x = torch.empty(3) #vector,1D
print(x)

tensor([9.0431e-38, 0.0000e+00, 7.6498e-35])


In [19]:
x = torch.empty(2,3) #matrix,2D
print(x)

tensor([[-3.1547e+02,  4.5577e-41,  7.6494e-35],
        [ 0.0000e+00, -3.3031e+23,  4.5576e-41]])


In [20]:
x = torch.empty(2,2,3) #tensor,3Dimensions
print(x)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  9.0432e-38,  0.0000e+00]],

        [[ 8.7208e-36,  0.0000e+00, -4.1043e+23],
         [ 4.5576e-41,  1.4013e-45,  0.0000e+00]]])


In [21]:
x = torch.empty(2,2,2,3) #tensor,4Dimensions
print(x)

tensor([[[[9.0410e-38, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 1.4013e-45],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[1.4013e-45, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 1.4013e-45, 0.0000e+00]],

         [[1.4013e-45, 0.0000e+00, 1.4013e-45],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]]])


In [22]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.7208, 0.1450, 0.3269],
        [0.2872, 0.3696, 0.9128],
        [0.0188, 0.5525, 0.2615],
        [0.2808, 0.7918, 0.1416],
        [0.8513, 0.7775, 0.2946]])


In [23]:
#torch.zeros(size), fill with 0
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [24]:
#torch.ones(size), fill with 1
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [25]:
# check data type
print(x.dtype)

torch.float32


In [26]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.int)
print(x.dtype)

torch.int32


In [27]:
# check size
print(x.size())

torch.Size([5, 3])


In [28]:
# construct from data
x =  torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [29]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


## Operations on Tensors

In [30]:
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print(y)
print(x)


tensor([[0.1153, 0.0792],
        [0.8690, 0.2238]])
tensor([[0.8583, 0.8356],
        [0.0665, 0.1346]])


In [31]:
#elementwise addition
z = x + y
print(z)
# z = torch.add(x,y)

tensor([[0.9736, 0.9148],
        [0.9355, 0.3584]])


In [32]:
# in place addition, everything with a trailing underscore is an inplace operation
# i.e. it will modify the variable
y.add_(x)
print(y)

tensor([[0.9736, 0.9148],
        [0.9355, 0.3584]])


In [33]:
# subtraction
z = x - y
print(z)
# z = torch.sub(x,y)

tensor([[-0.1153, -0.0792],
        [-0.8690, -0.2238]])


In [34]:
# multiplication
z = x * y
print(z)
# z = torch.mul(x,y)

tensor([[0.8356, 0.7645],
        [0.0623, 0.0482]])


In [35]:
# in place
y.mul_(x)
print(y)

tensor([[0.8356, 0.7645],
        [0.0623, 0.0482]])


In [36]:
# division
z = x / y
z = torch.div(x,y)

## Slicing

In [37]:
x = torch.rand(5,3)
print(x)

tensor([[0.8567, 0.6237, 0.1442],
        [0.1731, 0.4397, 0.4046],
        [0.4769, 0.2214, 0.5187],
        [0.6428, 0.3954, 0.5433],
        [0.9198, 0.2937, 0.3396]])


In [38]:
print(x[:, 0]) # all rows, column 0

tensor([0.8567, 0.1731, 0.4769, 0.6428, 0.9198])


In [39]:
print(x[1, :]) # row 1, all columns

tensor([0.1731, 0.4397, 0.4046])


In [40]:
print(x[1, 1]) # element at 1, 1

tensor(0.4397)


In [41]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.4396858215332031


## Reshape with `torch.view()`

In [42]:
x = torch.rand(4, 4)
print(x)

tensor([[0.7141, 0.0324, 0.4267, 0.3590],
        [0.6224, 0.2767, 0.5818, 0.4722],
        [0.3127, 0.5482, 0.0659, 0.2140],
        [0.9149, 0.1135, 0.9215, 0.3505]])


In [43]:
y = x.view(16)
print(y)

tensor([0.7141, 0.0324, 0.4267, 0.3590, 0.6224, 0.2767, 0.5818, 0.4722, 0.3127,
        0.5482, 0.0659, 0.2140, 0.9149, 0.1135, 0.9215, 0.3505])


In [44]:
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(z.size())

torch.Size([2, 8])


## Numpy
Converting a Torch Tensor to a NumPy array and vice versa is very easy

### torch to numpy with `.numpy()`

In [45]:
import numpy as np
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [46]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


### Careful!
If the Tensor is on the CPU (not the GPU), both objects will share the same memory location, so changing one will also change the other.

In [47]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### numpy to torch with `.from_numpy(x)`

In [48]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [49]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### Again be careful when modifying

In [50]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Move Tensors to GPU
By default all tensors are created on the CPU, but you can also move them to the GPU(only if it's available)

In [51]:
if torch.cuda.is_available():
  device = torch.device("cuda")         # a CUDA device object
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  # z.numpy()  ##error
  z = z.to("cpu")

## argument `requires_grad`
This will tell PyTorch that it will need to calculate the gradients for this tensor later in your optimization steps, i.e., this is a variable in your model that you want to optimize. This will be very important later in our training!



In [ ]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
