<a href="https://colab.research.google.com/github/OniOnizukazuka/PyTorchBeginner/blob/main/PyTorchBeginner02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Tensor Basics - PyTorch Beginner 02](https://www.python-engineer.com/courses/pytorchbeginner/01-installation/)

# **02 Tensor Basics**
This part covers the basics of Tensors and Tensor operations in PyTorch. Learn also how to convert from numpy data to PyTorch tensors and vice versa!

## Tensor
Everything in PyTorch is based on Tesor operations. A tensor can have different dimensions, so it can be 1d(scalar), 2d(vector), or even 3d(matrix) and higher. Let's have a look how we can create a tensor in PyTorch.

In [4]:
import torch

# torch.empty(size): uninitiallized
x = torch.empty(1) #scalar
print(x)
x = torch.empty(3) #vector,1D
print(x)
x = torch.empty(2,3) #matrix,2D
print(x)
x = torch.empty(2,2,3) #tensor,3Dimensions
print(x)
x = torch.empty(2,2,2,3) #tensor,4Dimensions
print(x)

tensor([4.2328e+21])
tensor([4.5921e-35, 0.0000e+00, 4.5919e-35])
tensor([[4.5929e-35, 0.0000e+00, 4.5927e-35],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])
tensor([[[ 4.5926e-35,  0.0000e+00, -5.8296e+35],
         [ 4.5644e-41,  8.9683e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00,  4.5935e-35],
         [ 0.0000e+00,  2.2912e-39,  9.4591e-39]]])
tensor([[[[-5.8296e+35,  4.5644e-41, -5.8296e+35],
          [ 4.5644e-41,  4.4842e-44,  0.0000e+00]],

         [[ 1.5695e-43,  0.0000e+00,  4.5924e-35],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 1.4013e-45,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  1.8077e-43,  0.0000e+00]]]])


In [5]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

#torch.zeros(size), fill with 0
#torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)
x = torch.ones(2, 3)
print(x)

tensor([[0.4299, 0.5985, 0.5158],
        [0.8278, 0.1780, 0.4131],
        [0.0552, 0.6528, 0.1216],
        [0.6458, 0.1489, 0.7448],
        [0.7405, 0.6231, 0.3300]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# check size
print(x.size())

# check data type
print(x.dtype)

# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# construct from data
x =  torch.tensor([5.5, 3])
print(x.size())

torch.Size([2, 3])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.Size([2])


## argument `requires_grad`
This will tell PyTorch that it will need to calculate the gradients for this tensor later in your optimization steps, i.e., this is a variable in your model that you want to optimize. This will be very important later in our training!

[grad(勾配)について](https://mathwords.net/graddivrot)<br>
[requires_grad](https://take-tech-engineer.com/pytorch-requires-grad/)

In [ ]:
x = torch.tensor([5.5, 3], requires_grad=True)

## Operations on Tensors

In [9]:
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print(y)
print(x)
#elementwise addition
z = x + y
print(z)
# torch.add(x,y)

# in place addition, everything with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# subtraction
z = x - y
z = torch.sub(x,y)
print(z)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

tensor([[0.6611, 0.5565],
        [0.6476, 0.1306]])
tensor([[0.9389, 0.1047],
        [0.4198, 0.7490]])
tensor([[1.6000, 0.6612],
        [1.0674, 0.8796]])
tensor([[ 0.2778, -0.4517],
        [-0.2279,  0.6184]])


## Slicing

In [ ]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1, 1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

tensor([[0.8291, 0.1977, 0.6505],
        [0.6647, 0.1387, 0.1594],
        [0.9829, 0.6869, 0.8140],
        [0.4897, 0.6545, 0.3775],
        [0.8679, 0.9331, 0.7910]])
tensor([0.8291, 0.6647, 0.9829, 0.4897, 0.8679])
tensor([0.6647, 0.1387, 0.1594])
tensor(0.1387)
0.13866758346557617


## Reshape with `torch.view()`

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## Numpy
Converting a Torch Tensor to a NumPy array and vice versa is very easy

### torch to numpy with `.numpy()`

In [ ]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


### Careful!
If the Tensor is on the CPU (not the GPU), both objects will share the same memory location, so changing one will also change the other.

In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### numpy to torch with `.from_numpy(x)`

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### Again be careful when modifying

In [ ]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Move Tensors to GPU
By default all tensors are created on the CPU, but you can also move them to the GPU(only if it's available)

In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")         # a CUDA device object
  y = torch.ones_like(x, device=device) # directly create a tensor on GPU
  x = x.to(device)                      # or just use strings  " .to("cuda") "
  z = x + y
  # z = z.numpy() # not possible because numpy cannot handle GPU tensors
  # move to CPU again
  z.to("cpu")     # " .to " can also change dtype together!
  # z = z.numpy()