<a href="https://colab.research.google.com/github/OniOnizukazuka/PyTorchBeginner/blob/main/PyTorchBeginner02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.python-engineer.com/courses/pytorchbeginner/01-installation/

# **02 Tensor Basics**

## Tensor

In [ ]:
import torch

# torch.empty(size): uninitiallized
x = torch.empty(1) #scalar
print(x)
x = torch.empty(3) #vector,1D
print(x)
x = torch.empty(2,3) #matrix,2D
print(x)
x = torch.empty(2,2,3) #tensor,3Dimensions
print(x)
x = torch.empty(2,2,2,3) #tensor,4Dimensions
print(x)

tensor([84993024.])
tensor([3.3190e-34, 0.0000e+00, 3.3216e-34])
tensor([[3.3266e-34, 0.0000e+00, 3.3264e-34],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[[3.3262e-34, 0.0000e+00, 3.3262e-34],
         [0.0000e+00, 8.9683e-44, 0.0000e+00]],

        [[1.1210e-43, 0.0000e+00, 3.3266e-34],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
tensor([[[[8.4994e+07, 4.5859e-41, 3.3261e-34],
          [0.0000e+00, 1.4013e-45, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[8.9683e-44, 0.0000e+00, 2.9287e-43],
          [0.0000e+00, 3.2855e-34, 0.0000e+00]],

         [[3.0276e-34, 0.0000e+00, 1.4013e-45],
          [0.0000e+00, 3.0980e-34, 0.0000e+00]]]])


In [ ]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

#torch.zeros(size), fill with 0
#torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)
x = torch.ones(2, 3)
print(x)

tensor([[0.8264, 0.8876, 0.3951],
        [0.4613, 0.6836, 0.6456],
        [0.3838, 0.3356, 0.7267],
        [0.6340, 0.7510, 0.5757],
        [0.5488, 0.0882, 0.2959]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# check size
print(x.size())

# check data type
print(x.dtype)

# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# construct from data
x =  torch.tensor([5.5, 3])
print(x.size())

torch.Size([2, 3])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.Size([2])


## argument `requires_grad`
This will tell PyTorch that it will need to calculate the gradients for this tensor later in your optimization steps, i.e., this is a variable in your model that you want to optimize. This will be very important later in our training!

[grad(勾配)について](https://mathwords.net/graddivrot)<br>
[requires_grad](https://take-tech-engineer.com/pytorch-requires-grad/)

In [ ]:
x = torch.tensor([5.5, 3], requires_grad=True)

## Operations on Tensors

In [ ]:
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print(y)
print(x)
#elementwise addition
z = x + y
print(z)
# torch.add(x,y)

# in place addition, everything with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# subtraction
z = x - y
z = torch.sub(x,y)
print(z)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

tensor([[0.1034, 0.1426],
        [0.6794, 0.2292]])
tensor([[0.2736, 0.3396],
        [0.0109, 0.1587]])
tensor([[0.3769, 0.4822],
        [0.6903, 0.3878]])
tensor([[ 0.1702,  0.1970],
        [-0.6685, -0.0705]])


## Slicing

In [ ]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1, 1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

tensor([[0.8291, 0.1977, 0.6505],
        [0.6647, 0.1387, 0.1594],
        [0.9829, 0.6869, 0.8140],
        [0.4897, 0.6545, 0.3775],
        [0.8679, 0.9331, 0.7910]])
tensor([0.8291, 0.6647, 0.9829, 0.4897, 0.8679])
tensor([0.6647, 0.1387, 0.1594])
tensor(0.1387)
0.13866758346557617


## Reshape with `torch.view()`

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## Numpy
Converting a Torch Tensor to a NumPy array and vice versa is very easy

### torch to numpy with `.numpy()`

In [ ]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


### Careful!
If the Tensor is on the CPU (not the GPU), both objects will share the same memory location, so changing one will also change the other.

In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### numpy to torch with `.from_numpy(x)`

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### Again be careful when modifying

In [ ]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Move Tensors to GPU
By default all tensors are created on the CPU, but you can also move them to the GPU(only if it's available)

In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")         # a CUDA device object
  y = torch.ones_like(x, device=device) # directly create a tensor on GPU
  x = x.to(device)                      # or just use strings  " .to("cuda") "
  z = x + y
  # z = z.numpy() # not possible because numpy cannot handle GPU tensors
  # move to CPU again
  z.to("cpu")     # " .to " can also change dtype together!
  # z = z.numpy()