<a href="https://colab.research.google.com/github/OniOnizukazuka/PyTorchBeginner/blob/main/PyTorchBeginner02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Tensor Basics - PyTorch Beginner 02](https://www.python-engineer.com/courses/pytorchbeginner/01-installation/)

# **02 Tensor Basics**
This part covers the basics of Tensors and Tensor operations in PyTorch. Learn also how to convert from numpy data to PyTorch tensors and vice versa!

## Tensor
Everything in PyTorch is based on Tesor operations. A tensor can have different dimensions, so it can be 1d(scalar), 2d(vector), or even 3d(matrix) and higher. Let's have a look how we can create a tensor in PyTorch.

In [3]:
import torch

x = torch.empty(1) #scalar
print(x)

tensor([234801.7500])


In [4]:
x = torch.empty(3) #vector,1D
print(x)

tensor([5.2135e-35, 0.0000e+00, 5.2117e-35])


In [5]:
x = torch.empty(2,3) #matrix,2D
print(x)

tensor([[5.2194e-35, 0.0000e+00, 5.2161e-35],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])


In [6]:
x = torch.empty(2,2,3) #tensor,3Dimensions
print(x)

tensor([[[5.2199e-35, 0.0000e+00, 2.3480e+05],
         [4.5678e-41, 8.9683e-44, 0.0000e+00]],

        [[1.1210e-43, 0.0000e+00, 5.2121e-35],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]]])


In [7]:
x = torch.empty(2,2,2,3) #tensor,4Dimensions
print(x)

tensor([[[[4.7373e-35, 0.0000e+00, 5.2198e-35],
          [0.0000e+00, 7.0976e+22, 2.1715e-18]],

         [[4.2330e+21, 1.6534e+19, 1.1625e+27],
          [1.4580e-19, 7.1856e+22, 4.3605e+27]]],


        [[[1.5766e-19, 7.1856e+22, 1.5835e-43],
          [0.0000e+00, 5.2196e-35, 0.0000e+00]],

         [[2.3480e+05, 4.5678e-41, 8.2733e+20],
          [5.3689e-05, 3.2540e+21, 1.0663e-08]]]])


In [8]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.1658, 0.2767, 0.9383],
        [0.7960, 0.9063, 0.7730],
        [0.1953, 0.9387, 0.5926],
        [0.1870, 0.1636, 0.6602],
        [0.1737, 0.9928, 0.3607]])


In [9]:
#torch.zeros(size), fill with 0
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
#torch.ones(size), fill with 1
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [11]:
# check data type
print(x.dtype)

torch.float32


In [13]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.int)
print(x.dtype)

torch.int32


In [14]:
# check size
print(x.size())

torch.Size([5, 3])


In [17]:
# construct from data
x =  torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


## argument `requires_grad`
This will tell PyTorch that it will need to calculate the gradients for this tensor later in your optimization steps, i.e., this is a variable in your model that you want to optimize. This will be very important later in our training!

[grad(勾配)について](https://mathwords.net/graddivrot)<br>
[requires_grad](https://take-tech-engineer.com/pytorch-requires-grad/)

In [ ]:
x = torch.tensor([5.5, 3], requires_grad=True)

## Operations on Tensors

In [18]:
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print(y)
print(x)


tensor([[0.2195, 0.7158],
        [0.8608, 0.5602]])
tensor([[0.9154, 0.9560],
        [0.9789, 0.9808]])


In [19]:
#elementwise addition
z = x + y
print(z)
# torch.add(x,y)

tensor([[1.1349, 1.6717],
        [1.8398, 1.5410]])


In [ ]:
# in place addition, everything with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# subtraction
z = x - y
z = torch.sub(x,y)
print(z)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

## Slicing

In [ ]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1, 1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

tensor([[0.8291, 0.1977, 0.6505],
        [0.6647, 0.1387, 0.1594],
        [0.9829, 0.6869, 0.8140],
        [0.4897, 0.6545, 0.3775],
        [0.8679, 0.9331, 0.7910]])
tensor([0.8291, 0.6647, 0.9829, 0.4897, 0.8679])
tensor([0.6647, 0.1387, 0.1594])
tensor(0.1387)
0.13866758346557617


## Reshape with `torch.view()`

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## Numpy
Converting a Torch Tensor to a NumPy array and vice versa is very easy

### torch to numpy with `.numpy()`

In [ ]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


### Careful!
If the Tensor is on the CPU (not the GPU), both objects will share the same memory location, so changing one will also change the other.

In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### numpy to torch with `.from_numpy(x)`

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### Again be careful when modifying

In [ ]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Move Tensors to GPU
By default all tensors are created on the CPU, but you can also move them to the GPU(only if it's available)

In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")         # a CUDA device object
  y = torch.ones_like(x, device=device) # directly create a tensor on GPU
  x = x.to(device)                      # or just use strings  " .to("cuda") "
  z = x + y
  # z = z.numpy() # not possible because numpy cannot handle GPU tensors
  # move to CPU again
  z.to("cpu")     # " .to " can also change dtype together!
  # z = z.numpy()